{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '0.0.4', 'description': 'This is a service Test Application', 'long_description': '', 'author': 'Rohit Khattar', 'author_email': 'rohitkhattar@gmail.com', 'url': 'https://github.com/rfun/tethysapp-servicetest.git', 'license': 'BSD 3-Clause License'}"
  dev_url: {{ data.get('url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: rohitkhattar@gmail.com
  keywords:
  - Tethys
  - App
  - Services
  - Cool
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run: null
source:
  path: ..
